export const Map_Name = {
  "Seoul" : "서울",
  "Busan" : "부산",
  "Daegu" : "대구",
  "Incheon": "인천",
  "Gwangju": "광주",
  "Daejeon": "대전",
  "Ulsan" : "울산",
  "Gyeonggi" : "경기",
  "Gangwon" : "강원",
  "North Chungcheong" : "충북",
  "South Chungcheong" : "충남",
  "North Jeolla" : "전북",
  "South Jeolla": "전남",
  "North Gyeongsang": "경북",
  "South Gyeongsang" : "경남",
  "Jeju": "제주",
  "Sejong" : "세종",
}

